<%@ Page Language="C#" MasterPageFile="~/Pohjoisnapa.master" AutoEventWireup="true"
	Inherits="Ilmastonmuutos" Title="Pohjoisnapa 2006 - Ilmastonmuutos" Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" Codebehind="Ilmastonmuutos.aspx.cs" %>

<asp:Content ID="ContentIlmastonmuutos" ContentPlaceHolderID="MainContent" runat="Server">
	<div class="artikkeli">
		<h4>
			<asp:Localize runat="server" ID="Otsikko" meta:resourcekey="OtsikkoResource1" Text="Ilmastonmuutos yleisesti"></asp:Localize></h4>
		<asp:Localize runat="server" ID="IlmastonmuutosTeksti" meta:resourcekey="IlmastonmuutosTekstiResource1" Text="&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Ilmaston muutokset pitkien aikojen kuluessa ovat luonnollisia. Nykyään ilmastonmuutoksena käsitetään&#13;&#10;&#9;&#9;&#9;pääasiassa suoraan tai epäsuorasti ihmisen toiminnasta aiheutuvaa epänormaalia ilmaston lämpenemistä.&#13;&#10;&#9;&#9;&#9;Viime aikoina tapahtuneen ilmaston poikkeavan lämpenemisen katsotaan johtuvan ihmisen toiminnasta, erityisesti&#13;&#10;&#9;&#9;&#9;teollisuuden päästöistä sekä metsien vähenemisestä maailmanlaajuisesti.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Ihmisen aikaansaamaa muutosta kuvataan myös kasvihuoneilmiöksi. Kasvihuoneilmiö syntyy siitä, että lämpöenergiaa&#13;&#10;&#9;&#9;&#9;tuottavat auringonsäteet pääsevät maapallolle ilmakehän (ja otsonikerroksen) läpi voimakkaammin kuin&#13;&#10;&#9;&#9;&#9;ennen, mutta johtuen kasvaneesta kasvihuonekaasujen (esim. hiilidioksidi ja metaani) määrästä ilmakehässä&#13;&#10;&#9;&#9;&#9;lämpöä ei enää pääse maapallolta pois kuten aiemmin. Lämpö ”varastoituu” ilmakehän esteiden vuoksi.&#13;&#10;&#9;&#9;&#9;Tämä lämmittää ilmastoa koko maapallolla siten, että eri alueet lämpenevät eri tavalla. Erityisesti&#13;&#10;&#9;&#9;&#9;lämpenevät kaikki manneralueet ja kaikkein merkittävimmin pohjoiset maa- ja napa-alueet.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Hiilidioksidin ja metaanin lisäksi tärkeimpiä kasvihuonekaasuja ovat dityppioksidit ja halogenoidut&#13;&#10;&#9;&#9;&#9;hiilivedyt eli CFC-yhdisteet. CFC-yhdisteet eivät esiinny luonnossa ja ne ovat peräisin ihmistoiminnasta.&#13;&#10;&#9;&#9;&#9;Ko. aineiden vaikutus kasvihuoneilmiössä perustuu siihen, että ne tuhoavat otsonikerrosta, jolloin suurempi&#13;&#10;&#9;&#9;&#9;osa auringon (vahingollisesta) säteilystä pääsee maapallolle. Vaikka hiilidioksidin määrän nousu on&#13;&#10;&#9;&#9;&#9;suurin kasvihuoneilmiötä aiheuttava tekijä, metaanin, dityppioksidin ja halogenoitujen hiilivetyjen&#13;&#10;&#9;&#9;&#9;määrien muutos on hälyttävää niiden ollessa jopa kymmeniä kertoja voimakkaampia kasvihuonekaasuja kuin&#13;&#10;&#9;&#9;&#9;hiilidioksidi. Metaanipäästöistä 70 % on ihmisen toiminnasta peräisin.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Keskilämpötilat ovat nousseet 1800-luvun lopulta lähtien. Useiden eri arvioiden (mm. kansainvälinen&#13;&#10;&#9;&#9;&#9;ilmastopaneeli IPCC) mukaan maapallon keskilämpötilan arvioidaan nousevan 1,5 – 6 astetta vuoteen 2100&#13;&#10;&#9;&#9;&#9;mennessä. Lämpeneminen vaikuttaa jäätiköiden sulamisen kautta valtamerten pinnan nousuun ja merivirtojen&#13;&#10;&#9;&#9;&#9;muutoksiin sekä eri mallien mukaan mm. sademääriin siten, että kuivat lämpimät alueet kuivuvat lisää&#13;&#10;&#9;&#9;&#9;ja sateisilla alueilla (mm. Pohjois-Eurooppa) sademäärät kasvavat huomattavasti aiheuttaen tulvia.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;"></asp:Localize>
		<p style="width: 100%; text-align: right; margin-bottom: 15px;">
			<asp:HyperLink runat="server" ID="LinkkiSeuraavaSivu" NavigateUrl="~/IlmastonmuutosArktisillaAlueilla.aspx" meta:resourcekey="LinkkiSeuraavaSivuResource1">
			Seuraavaksi: "Ilmastonmuutos arktisilla alueilla" &gt;</asp:HyperLink>
		</p>
	</div>
</asp:Content>
