<%@ Page Language="C#" MasterPageFile="~/Pohjoisnapa.master" AutoEventWireup="true"
	Inherits="Valokuvaus" Title="Pohjoisnapa 2006 - Valokuvaus" Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" Codebehind="Valokuvaus.aspx.cs" %>

<asp:Content ID="ContentValokuvaus" ContentPlaceHolderID="MainContent" runat="Server">
	<div class="paivakirja">
		<p class="poikkeus2">
			<asp:Image runat="server" ID="OtsikkoKuva" ImageUrl="~/kuvat/linkit/otsikot/otsikko-valokuvaus.gif" Width="185px" Height="16px" AlternateText="Valokuvaus" meta:resourcekey="OtsikkoKuvaResource1" /></p>
			
		<h4>
			<asp:Localize runat="server" ID="Otsikko" meta:resourcekey="OtsikkoResource1" Text="Arktinen valokuvaus"></asp:Localize></h4>
		<asp:Localize runat="server" ID="Teksti" meta:resourcekey="TekstiResource1" Text="&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;TV- ja valokuvaus arktisella retkikunnalla eroaa monin tavoin tavallisesta sunnuntainäppäilystä.</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Valokuvaajan arkipäivää ovat jatkuvasti palelevat ja jäätyneet sormet. Kolmekymmen asteinen metallikamera&#13;&#10;&#9;&#9;&#9;kun tuntuu kylmältä. Kamera taas valittaa jatkuvasti heikoista paristoista tai akuista. Jos kaikki muuten&#13;&#10;&#9;&#9;&#9;taas on hyvin, niin vähintään kalusto on lumessa. Pakkasessa olevia kameroita ei tiivistyvän kondessioveden&#13;&#10;&#9;&#9;&#9;takia kannata usein lämmittää, joten sisäkuvat teltoista jäävät vähiin.</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Lähes yöttömässä yössä ei valon riittävyys kuvaamisen kannalta ole ongelma, paremminkin päinvastoin.&#13;&#10;&#9;&#9;&#9;Sen sijaan ongelmia tulee pilvisillä keleillä kontrastin ollessa olematon.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Kun kuvaaja hiihtää retkikunnan mukana vetäen muiden tapaan koko ajan ahkiota perässään, vaatii käytännön&#13;&#10;&#9;&#9;&#9;toiminta totuttelua, viitseliäisyyttä ja toisinaan pitkää pinnaa. Hyvien kuvien saaminen vaatii jatkuvaa&#13;&#10;&#9;&#9;&#9;ennakointia, jotta kuvaaja olisi valmiina sopivan lumilohkareen takana retkikunnan hiihtäessä ohi. Usein&#13;&#10;&#9;&#9;&#9;paras tapa ehtiä edelle, on tinkiä tauosta ja lähteä liikkeelle muutama minuutti etuajassa. Joka tapauksessa&#13;&#10;&#9;&#9;&#9;kuvaus on jatkuvaa singahtelua retkikunnan ympärillä tehden matkan teosta mielekästä joskin paikoin&#13;&#10;&#9;&#9;&#9;erittäin rankkaa ja valitettavasti siitä huolimatta suurin osa kuvista otetaan takavinkkelistä.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Parhaat kuvat syntyvät yleensä huonoimmassa mahdollisessa kelissä, joten viimeistään myrskyn pauhatessa&#13;&#10;&#9;&#9;&#9;ja pakkasen paukkuessa vaaditaan kuvaajalta melkoisenn paljon viitseliäisyyttä kaivaa kamera esiin ja ottaa&#13;&#10;&#9;&#9;&#9;kuvia.</p>&#13;&#10;&#9;&#9;"></asp:Localize>
	</div>
	<asp:Image runat="server" ID="Fiiliskuva" CssClass="paivakirjakuva" ImageUrl="~/kuvat/jpg/hiihto-vastavaloon.jpg" AlternateText="Vielä on matkaa" Width="360px" Height="250px" meta:resourcekey="FiiliskuvaResource1" />
</asp:Content>
