<%@ Page Language="C#" MasterPageFile="~/Pohjoisnapa.master" AutoEventWireup="true"
	Inherits="Ruoka" Title="Pohjoisnapa 2006 - Ruoka" Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" Codebehind="Ruoka.aspx.cs" %>

<asp:Content ID="ContentRuoka" ContentPlaceHolderID="MainContent" runat="Server">
	<div class="paivakirja">
		<p class="poikkeus2">
			<asp:Image runat="server" ID="OtsikkoKuva" ImageUrl="~/kuvat/linkit/otsikot/otsikko-ruoka.gif" Width="185px" Height="16px" meta:resourcekey="OtsikkoKuvaResource1" /></p>
		<h4>
			<asp:Localize runat="server" ID="Otsikko" meta:resourcekey="OtsikkoResource1" Text="Arktinen ruokavalio"></asp:Localize></h4>
		<asp:Localize runat="server" ID="Teksti" meta:resourcekey="TekstiResource1" Text="&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Suurin osa ruokavalion energiasta tulee voista. Sen syömisessä on oma työnsä, sillä voita varataan puolikiloa&#13;&#10;&#9;&#9;&#9;paria ja päivää kohden. Suoli vain tuppaa liukastumaan hieman normaalia nopeammaksi.</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Lounaalla nautitaan yksi pakastekuivattu ruokapussi per henki. Pussiin vain kaadetaan termospullosta&#13;&#10;&#9;&#9;&#9;kuuma vesi, odotellaan hetki, ja syödään.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Päivälliseksi/iltapalaksi tehdään kunnon ruoka. Perusraaka-aineena on pasta, riisi tai perunamuusi,&#13;&#10;&#9;&#9;&#9;ja sekaan käytetään erilaisia kuivatuotteita (karibun lihaa, valmiskastikepusseja, valmiskeittopusseja),&#13;&#10;&#9;&#9;&#9;sekä voita, juustoa, pekonia ja metwurstia. Viimeisten pilkkomisessa on ollut useasti ikävä kirvestä,&#13;&#10;&#9;&#9;&#9;tuotteet kun ovat kunnon syväjäässä eikä niihin tahdo puukko tepsiä.&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Eväillä kukin retkikunnan jäsen vetää perässään noin 1,1kg ruokaa per päivä, josta saa noin 6000 - 7000&#13;&#10;&#9;&#9;&#9;kCal energiaa. Ja silti kilot karisevat vyötäröltä; arktista retkeilyä suositellaan kaikille syömisestä&#13;&#10;&#9;&#9;&#9;pitäville mutta laihtumista toivoville. Ahkiossa vedetään luonnollisesti myös ruuan valmistamiseen tarvittava&#13;&#10;&#9;&#9;&#9;polttoaine, jota on noin 400g per henki per päivä.</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Lopuksi vielä jokaiselle kotiin kokeiltavaksi pieni aamuherkku:</p>&#13;&#10;&#9;&#9;"></asp:Localize>
	</div>
	<asp:Image runat="server" ID="FiilisKuva" ImageUrl="~/kuvat/jpg/tero-ja-perttu-syo.jpg" CssClass="paivakirjakuva" AlternateText="Tero ja Perttu aamupuurolla"
		Width="360px" Height="270px" meta:resourcekey="FiilisKuvaResource1" />
	<div class="puoliblokki oikea">
		<h4>
			<asp:Localize runat="server" ID="OtsikkoRuokaohje" meta:resourcekey="OtsikkoRuokaohjeResource1" Text="Pertun ja Teron aamupuuro"></asp:Localize></h4>
		<asp:Localize runat="server" ID="Ruokaohje" meta:resourcekey="RuokaohjeResource2" Text="&#13;&#10;&#9;&#9;<ul>&#13;&#10;&#9;&#9;&#9;<li>227 g voita paloiksi pilkottuna (puoli paikallista pakettia)</li>&#13;&#10;&#9;&#9;&#9;<li>2 dl kaurahiutaleita tai muita puurohiutaleita</li>&#13;&#10;&#9;&#9;&#9;<li>1,5 dl mysliä</li>&#13;&#10;&#9;&#9;&#9;<li>1 dl riisiä</li>&#13;&#10;&#9;&#9;&#9;<li>1 dl soijarouhetta</li>&#13;&#10;&#9;&#9;&#9;<li>1 dl sokeria</li>&#13;&#10;&#9;&#9;&#9;<li>0,5 dl maitojauhetta</li>&#13;&#10;&#9;&#9;&#9;<li>1 pss valmiskiisseliä (mustikka, vadelma tai mansikka)</li>&#13;&#10;&#9;&#9;&#9;<li>kourallinen rusinoita</li>&#13;&#10;&#9;&#9;&#9;<li>1,5 l vettä</li>&#13;&#10;&#9;&#9;</ul>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Kaikki ainekset sekoitetaan ja kiehautetaan, jonka jälken kattila nostetaan tulelta ja peitetään kannella.&#13;&#10;&#9;&#9;&#9;Odotetaan noin 15 min ja sekoitetaan. Voidaan koristella/maustaa pepperonilla, juustolla, pekonilla,&#13;&#10;&#9;&#9;&#9;tai millä vain käsiin sattuvalla ruokatuotteella. Nautitaan hyvässä seurassa, epämiellyttävässä asennossa,&#13;&#10;&#9;&#9;&#9;ja mieluiten pienessä kiireessä. Palan painikkeeksi sopii näkkileipä ja kaakao.</p>&#13;&#10;&#9;&#9;"></asp:Localize>
	</div>
</asp:Content>
