<%@ Page Language="C#" MasterPageFile="~/Pohjoisnapa.master" AutoEventWireup="true"
	Inherits="Suunnistus" Title="Pohjoisnapa 2006 - Suunnistus" Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" Codebehind="Suunnistus.aspx.cs" %>

<asp:Content ID="ContentSuunnistus" ContentPlaceHolderID="MainContent" runat="Server">
	<div class="paivakirja" id="texti">
		<p class="poikkeus2">
			<asp:Image runat="server" ID="OtsikkoKuva" ImageUrl="~/kuvat/linkit/otsikot/otsikko-suunnistus.gif" Width="185px" Height="16px" meta:resourcekey="OtsikkoKuvaResource1" /></p>
		<h4>
			<asp:Localize runat="server" ID="Otsikko" meta:resourcekey="OtsikkoResource1" Text="Suunnistus"></asp:Localize></h4>
		<asp:Localize runat="server" ID="Teksti" meta:resourcekey="TekstiResource1" Text='&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Miten napa-alueilla suunnistetaan kun ymp‰rill‰ ei ole kuin j‰‰lakeus&#13;&#10;&#9;&#9;&#9;ja kompassi toimii tuuliviirin lailla?&#13;&#10;&#9;&#9;</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Suunnistamme k‰yt‰nnˆss‰ auringon ja varjojen avulla. T‰m‰ touhu eroaa hieman kes‰isist‰ iltarasteista&#13;&#10;&#9;&#9;&#9;muutenkin kuin s‰‰n puolesta: karttojemme mittakaavat ovat 1:1 000 000 ja 1: 500 000 eik‰ rasteja ole&#13;&#10;&#9;&#9;&#9;piilotettu kuusenn‰reitten alle. Periaatteenamme on - karkeesti oikeaan suuntaan ja illalla GPS:st‰&#13;&#10;&#9;&#9;&#9;katsotaan mihin jouduttiin. P‰iv‰ss‰ kun ei ehdi hirveesti harhaan hiiht‰m‰‰n.</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Suunta otetaan <a href="#footnote1">legin<sup>1</sup></a> alussa ja se yritet‰‰n pit‰‰ samalla kun haetaan sopivaa reitti‰ lumikokkareiden&#13;&#10;&#9;&#9;&#9;joukosta. P‰iv‰n ensimm‰isell‰ legill‰ mies asettaa suksensa esim. 60 astetta varjosta oikealle ja antaa&#13;&#10;&#9;&#9;&#9;paahtaa. Toisella legill‰ varjo on en‰‰ 45 astetta hiiht‰j‰n vasemmalla puolella ja kolmannella 30 astetta&#13;&#10;&#9;&#9;&#9;jne. Ruokatauolla kuudennen legin j‰lkeen voidaan suuntaa hieman s‰‰t‰‰, jos tarvetta on tai ei ole&#13;&#10;&#9;&#9;&#9;muita virikkeit‰.</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Jos aurinko ja varjot katoavat pilviverhon taa, voi kulkusuuntaa karkeasti seurata tuulesta eli suunta&#13;&#10;&#9;&#9;&#9;on tuulesta temmattu. T‰llˆin kaikki odottavat illalla suurella mielenkiinnolla mihin oikein tultiin.</p>&#13;&#10;&#9;&#9;<p>&#13;&#10;&#9;&#9;&#9;Tilannetta, jossa ei tuule eik‰ taivas anna merkkej‰ auringosta, emme l‰hde t‰ss‰ yksityiskohtaisesti&#13;&#10;&#9;&#9;&#9;selvitt‰m‰‰n, sill‰ se selvi‰‰ aikanaan - myˆs meille.</p>&#13;&#10;&#9;&#9;'></asp:Localize>
		<div class="footnote">
			<asp:Localize runat="server" ID="Alaviite" meta:resourcekey="AlaviiteResource1" Text='&#13;&#10;&#9;&#9;&#9;--&#13;&#10;&#9;&#9;&#9;<p id="footnote1">&#13;&#10;&#9;&#9;&#9;&#9;<sup>1</sup> <i>Legi</i>: Retkikunnan k‰ytt‰m‰ nimitys kahden tauon v‰lill‰ kuljetusta matkasta. Yleens‰&#13;&#10;&#9;&#9;&#9;&#9;legi kest‰‰ 55 minuuttia, ja sin‰ aikana ehdit‰‰n maastosta riippuen hiiht‰‰ 0,5-3 km.&#13;&#10;&#9;&#9;&#9;</p>&#13;&#10;&#9;&#9;&#9;'></asp:Localize>
		</div>
	</div>
	<asp:Image runat="server" ID="Fiiliskuva" ImageUrl="~/kuvat/jpg/ahtojaissa-jermi.jpg" CssClass="paivakirjakuva" AlternateText="Tero ahtoj‰iss‰" Width="360px" Height="273px" meta:resourcekey="FiiliskuvaResource1" />
</asp:Content>
