//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Web.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arktiksen historia..
        /// </summary>
        internal static string arktisHistoria_description {
            get {
                return ResourceManager.GetString("arktisHistoria.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        internal static string arktisHistoria_title {
            get {
                return ResourceManager.GetString("arktisHistoria.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa arktiksella tapahtuvasta ilmastonmuutoksesta..
        /// </summary>
        internal static string arktisIlmastoYleinen_description {
            get {
                return ResourceManager.GetString("arktisIlmastoYleinen.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilmastonmuutos.
        /// </summary>
        internal static string arktisIlmastoYleinen_title {
            get {
                return ResourceManager.GetString("arktisIlmastoYleinen.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa arktiksella tapahtuvasta ilmastonmuutoksesta..
        /// </summary>
        internal static string arktisIlmasto_description {
            get {
                return ResourceManager.GetString("arktisIlmasto.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilmastonmuutos arktisilla alueilla.
        /// </summary>
        internal static string arktisIlmasto_title {
            get {
                return ResourceManager.GetString("arktisIlmasto.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa jääkarhun elintavoista..
        /// </summary>
        internal static string arktisJaakarhu_description {
            get {
                return ResourceManager.GetString("arktisJaakarhu.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jääkarhu.
        /// </summary>
        internal static string arktisJaakarhu_title {
            get {
                return ResourceManager.GetString("arktisJaakarhu.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoja arktiksen olosuhteista..
        /// </summary>
        internal static string arktisOlosuhteet_description {
            get {
                return ResourceManager.GetString("arktisOlosuhteet.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olosuhteet.
        /// </summary>
        internal static string arktisOlosuhteet_title {
            get {
                return ResourceManager.GetString("arktisOlosuhteet.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitkän arktisen vaelluksen ruokavalio..
        /// </summary>
        internal static string arktisRuoka_description {
            get {
                return ResourceManager.GetString("arktisRuoka.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruoka.
        /// </summary>
        internal static string arktisRuoka_title {
            get {
                return ResourceManager.GetString("arktisRuoka.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suunnistus arktisilla alueilla..
        /// </summary>
        internal static string arktisSuunnistus_description {
            get {
                return ResourceManager.GetString("arktisSuunnistus.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suunnistus.
        /// </summary>
        internal static string arktisSuunnistus_title {
            get {
                return ResourceManager.GetString("arktisSuunnistus.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valokuvaus kylmässä..
        /// </summary>
        internal static string arktisValokuvaus_description {
            get {
                return ResourceManager.GetString("arktisValokuvaus.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valokuvaus.
        /// </summary>
        internal static string arktisValokuvaus_title {
            get {
                return ResourceManager.GetString("arktisValokuvaus.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa arktiksesta..
        /// </summary>
        internal static string arktis_description {
            get {
                return ResourceManager.GetString("arktis.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arktis.
        /// </summary>
        internal static string arktis_title {
            get {
                return ResourceManager.GetString("arktis.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuvagalleria, jossa ennen hiihdon alkua otetut kuvat..
        /// </summary>
        internal static string galleriaEnnenHiihto_description {
            get {
                return ResourceManager.GetString("galleriaEnnenHiihto.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuvagalleria.
        /// </summary>
        internal static string galleriaEnnenHiihto_title {
            get {
                return ResourceManager.GetString("galleriaEnnenHiihto.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuvagalleria, jossa hiihdon aikana otetut kuvat..
        /// </summary>
        internal static string galleriaHiihto_description {
            get {
                return ResourceManager.GetString("galleriaHiihto.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiihdon aikaiset kuvat.
        /// </summary>
        internal static string galleriaHiihto_title {
            get {
                return ResourceManager.GetString("galleriaHiihto.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuvagalleria, jossa kuvia aikaisemmilta retkikunnilta..
        /// </summary>
        internal static string galleria_description {
            get {
                return ResourceManager.GetString("galleria.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuvia aikaisemmilta retkikunnilta.
        /// </summary>
        internal static string galleria_title {
            get {
                return ResourceManager.GetString("galleria.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.pohjoisnapa.fi -etusivu.
        /// </summary>
        internal static string home_description {
            get {
                return ResourceManager.GetString("home.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etusivu.
        /// </summary>
        internal static string home_title {
            get {
                return ResourceManager.GetString("home.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunnan medianäkyvyys..
        /// </summary>
        internal static string media_description {
            get {
                return ResourceManager.GetString("media.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medianäkyvyys.
        /// </summary>
        internal static string media_title {
            get {
                return ResourceManager.GetString("media.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapaa retkikunnan jäsenet..
        /// </summary>
        internal static string messut_description {
            get {
                return ResourceManager.GetString("messut.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapahtumat.
        /// </summary>
        internal static string messut_title {
            get {
                return ResourceManager.GetString("messut.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa keleistä ja etenemisvauhdeista..
        /// </summary>
        internal static string paivakirjaData_description {
            get {
                return ResourceManager.GetString("paivakirjaData.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string paivakirjaData_title {
            get {
                return ResourceManager.GetString("paivakirjaData.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kaikista päiväkirjamerkinnöistä aikajärjestyksessä..
        /// </summary>
        internal static string paivakirjaKaikki_description {
            get {
                return ResourceManager.GetString("paivakirjaKaikki.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaikki päiväkirjaotteet.
        /// </summary>
        internal static string paivakirjaKaikki_title {
            get {
                return ResourceManager.GetString("paivakirjaKaikki.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sijainti kartalla.
        /// </summary>
        internal static string paivakirjaKartta_description {
            get {
                return ResourceManager.GetString("paivakirjaKartta.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartta.
        /// </summary>
        internal static string paivakirjaKartta_title {
            get {
                return ResourceManager.GetString("paivakirjaKartta.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pohjoisnapa - jäinen haaste. .
        /// </summary>
        internal static string paivakirjaKirja_description {
            get {
                return ResourceManager.GetString("paivakirjaKirja.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirja.
        /// </summary>
        internal static string paivakirjaKirja_title {
            get {
                return ResourceManager.GetString("paivakirjaKirja.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilaa kirja Pohjoisnapa - jäinen haaste.
        /// </summary>
        internal static string paivakirjaTilaaKirja_description {
            get {
                return ResourceManager.GetString("paivakirjaTilaaKirja.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilaa kirja.
        /// </summary>
        internal static string paivakirjaTilaaKirja_title {
            get {
                return ResourceManager.GetString("paivakirjaTilaaKirja.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuorein retkikunnan lähettämä päiväkirjaote..
        /// </summary>
        internal static string paivakirjaViimeisin_description {
            get {
                return ResourceManager.GetString("paivakirjaViimeisin.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuorein päiväkirjaote.
        /// </summary>
        internal static string paivakirjaViimeisin_title {
            get {
                return ResourceManager.GetString("paivakirjaViimeisin.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Päiväkirjamerkinnät sekä tietoa keleistä ja etenemisvauhdista..
        /// </summary>
        internal static string paivakirja_description {
            get {
                return ResourceManager.GetString("paivakirja.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Päiväkirja.
        /// </summary>
        internal static string paivakirja_title {
            get {
                return ResourceManager.GetString("paivakirja.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunnan aikataulu.
        /// </summary>
        internal static string retkikuntaAikataulu_description {
            get {
                return ResourceManager.GetString("retkikuntaAikataulu.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aikataulu.
        /// </summary>
        internal static string retkikuntaAikataulu_title {
            get {
                return ResourceManager.GetString("retkikuntaAikataulu.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laskuvarjojääkärikilta.
        /// </summary>
        internal static string retkikuntaLsvjk {
            get {
                return ResourceManager.GetString("retkikuntaLsvjk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa Laskuvarjojääkärikillasta..
        /// </summary>
        internal static string retkikuntaLsvjk_description {
            get {
                return ResourceManager.GetString("retkikuntaLsvjk.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa retkikunnan taustoista..
        /// </summary>
        internal static string retkikuntaTaustaa_description {
            get {
                return ResourceManager.GetString("retkikuntaTaustaa.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taustaa.
        /// </summary>
        internal static string retkikuntaTaustaa_title {
            get {
                return ResourceManager.GetString("retkikuntaTaustaa.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunnan tavoitteet..
        /// </summary>
        internal static string retkikuntaTavoitteet_description {
            get {
                return ResourceManager.GetString("retkikuntaTavoitteet.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavoitteet.
        /// </summary>
        internal static string retkikuntaTavoitteet_title {
            get {
                return ResourceManager.GetString("retkikuntaTavoitteet.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lääketieteellinen tutkimus..
        /// </summary>
        internal static string retkikuntaTutkimus_description {
            get {
                return ResourceManager.GetString("retkikuntaTutkimus.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutkimus.
        /// </summary>
        internal static string retkikuntaTutkimus_title {
            get {
                return ResourceManager.GetString("retkikuntaTutkimus.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunnan keitinvalinta ja tietoa veden sulatuksesta vaativissa telttaolosuhteissa..
        /// </summary>
        internal static string retkikuntaVarusteetKeitin_description {
            get {
                return ResourceManager.GetString("retkikuntaVarusteetKeitin.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keitin.
        /// </summary>
        internal static string retkikuntaVarusteetKeitin_title {
            get {
                return ResourceManager.GetString("retkikuntaVarusteetKeitin.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunnan käyttämät varusteet.
        /// </summary>
        internal static string retkikuntaVarusteet_description {
            get {
                return ResourceManager.GetString("retkikuntaVarusteet.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varusteet.
        /// </summary>
        internal static string retkikuntaVarusteet_title {
            get {
                return ResourceManager.GetString("retkikuntaVarusteet.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoa retkikunnasta ja sen taustoista..
        /// </summary>
        internal static string retkikunta_description {
            get {
                return ResourceManager.GetString("retkikunta.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunta.
        /// </summary>
        internal static string retkikunta_title {
            get {
                return ResourceManager.GetString("retkikunta.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunnan tukijat..
        /// </summary>
        internal static string tukijatLista_description {
            get {
                return ResourceManager.GetString("tukijatLista.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tukijalista.
        /// </summary>
        internal static string tukijatLista_title {
            get {
                return ResourceManager.GetString("tukijatLista.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retkikunnan tukijat..
        /// </summary>
        internal static string tukijat_description {
            get {
                return ResourceManager.GetString("tukijat.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tukijat.
        /// </summary>
        internal static string tukijat_title {
            get {
                return ResourceManager.GetString("tukijat.title", resourceCulture);
            }
        }
    }
}
